[package]
name = "glum-backend"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
jsonwebtoken = "9"
reqwest = { version = "0.12", features = ["json"] }
serde_json = "1"
time = "0.3"
tokio = { version = "1", features = ["full"] }
tonic = "0.12"
prost = "0.13"
prost-types = "0.13"
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio", "migrate", "uuid", "time"] }
serde = { version = "1", features = ["derive"] }
uuid = { version = "1", features = ["v4"] }

tonic-reflection = "0.12"

[build-dependencies]
tonic-build = "0.12"
